/**
 * myrmidon(G5): stdout captured from the installed Hermes CLI (v0.21.x),
 * run without `-Q` against a local mock of an OpenAI-compatible provider
 * (`hermes chat --query-file - --source tool --yolo`, stdin not a tty).
 *
 * Used by the live-progress tests instead of hand-built frames, so the parser
 * is checked against the shapes the CLI really prints — the streaming boxes,
 * the `box.HORIZONTALS` Panels, the `❌` narration lines around a failed turn,
 * the divider, the inline tool diff and the exit summary — with the CR/LF
 * mix the terminal layer produces preserved (`\r\n` on Rich/tool output,
 * `\n` on the exit summary). Only environment specifics were rewritten:
 * workspace paths became `/workspace`, the provider endpoint became
 * `provider.example.com`, and session ids became fixed neutral values. Every
 * capture exited with code 0, including the failed ones — that is the
 * defect the failure detection exists for.
 *
 * Not a test file (no `.test.` in the name), so vitest does not collect it.
 */

/** A successful turn with three tool calls (terminal, write_file with a diff, terminal) and streamed commentary between them: three intermediate streaming boxes, then the answer box. */
export const REAL_MULTI_TOOL_SUCCESS: string = [
  "Query: Fix the null check in session.ts and report.",
  "Initializing agent...\r",
  "────────────────────────────────────────\r",
  "",
  "\r",
  "╭─ ⚕ Hermes ───────────────────────────────────────────────────────────────────╮\r",
  "Let me look at the session lookup code first.\r",
  "╰──────────────────────────────────────────────────────────────────────────────╯\r",
  "  ┊ 💻 preparing terminal…\r",
  "  ┊ 💻 $         cat /workspace/session.ts  0.1s\r",
  "\r",
  "╭─ ⚕ Hermes ───────────────────────────────────────────────────────────────────╮\r",
  "Found it. Now applying the fix.\r",
  "╰──────────────────────────────────────────────────────────────────────────────╯\r",
  "  ┊ ✍️ preparing write_file…\r",
  "  ┊ ✍️  write     /workspace/session.ts  1.3s\r",
  "  ┊ review diff\r",
  "a/session.ts → b/session.ts\r",
  "@@ -1,5 +1,5 @@\r",
  " export function lookup(session) {\r",
  "-  if (session) {\r",
  "+  if (session && session.isValid) {\r",
  "     return session.id;\r",
  "   }\r",
  "   return null;\r",
  "\r",
  "╭─ ⚕ Hermes ───────────────────────────────────────────────────────────────────╮\r",
  "Verifying the change.\r",
  "╰──────────────────────────────────────────────────────────────────────────────╯\r",
  "  ┊ 💻 preparing terminal…\r",
  "  ┊ 💻 $         cat /workspace/session.ts  0.0s\r",
  "\r",
  "╭─ ⚕ Hermes ───────────────────────────────────────────────────────────────────╮\r",
  "Fixed the missing null check in the session lookup.\r",
  "\r",
  "- Verified with a targeted run\r",
  "- Updated the changelog entry\r",
  "╰──────────────────────────────────────────────────────────────────────────────╯\r",
  "",
  "Resume this session with:",
  "  hermes --resume 20260101_120000_a1b2c3",
  "  hermes -c \"Mock title\"",
  "",
  "Session:        20260101_120000_a1b2c3",
  "Title:          Mock title",
  "Duration:       4s",
  "Messages:       8 (1 user, 6 tool calls)",
  "",
].join("\n");

/** A successful turn with no tool call: a single streaming box. */
export const REAL_SIMPLE_SUCCESS: string = [
  "Query: Fix the null check in session.ts and report.",
  "Initializing agent...\r",
  "  ⚠ tirith security scanner enabled but not available — command scanning will use pattern matching only\r",
  "────────────────────────────────────────\r",
  "",
  "\r",
  "╭─ ⚕ Hermes ───────────────────────────────────────────────────────────────────╮\r",
  "Fixed the missing null check in the session lookup.\r",
  "\r",
  "- Verified with a targeted run\r",
  "- Updated the changelog entry\r",
  "╰──────────────────────────────────────────────────────────────────────────────╯\r",
  "",
  "Resume this session with:",
  "  hermes --resume 20260101_120000_a1b2c3",
  "  hermes -c \"Mock title\"",
  "",
  "Session:        20260101_120000_a1b2c3",
  "Title:          Mock title",
  "Duration:       3s",
  "Messages:       2 (1 user, 0 tool calls)",
  "",
].join("\n");

/** A provider refusal for exhausted credits (HTTP 402): non-retryable narration, an error Panel, then the second "Out of credits" Panel. */
export const REAL_FAILED_402_WITH_CALL_TO_ACTION: string = [
  "Query: Fix the null check in session.ts and report.",
  "Initializing agent...\r",
  "  ⚠ tirith security scanner enabled but not available — command scanning will use pattern matching only\r",
  "────────────────────────────────────────\r",
  "",
  "⚠️  API call failed (attempt 1/3): APIStatusError [HTTP 402]\r",
  "   🔌 Provider: custom  Model: mock-model\r",
  "   🌐 Endpoint: http://provider.example.com/v1\r",
  "   📝 Error: HTTP 402: Insufficient credits: billing required\r",
  "   📋 Details: {'message': 'Insufficient credits: billing required', 'type': 'billing', 'code': 'insufficient_quota'}\r",
  "   ⏱️  Elapsed: 0.35s  Context: 2 msgs, ~1,302 tokens\r",
  "❌ Non-retryable error (HTTP 402): HTTP 402: Insufficient credits: billing required\r",
  "❌ Non-retryable client error (HTTP 402). Aborting.\r",
  "   🔌 Provider: custom  Model: mock-model\r",
  "   🌐 Endpoint: http://provider.example.com/v1\r",
  "   💡 Custom reported that billing, credits, or account entitlement is exhausted for mock-model.\r",
  "   💡 Add credits or update billing with that provider, then retry.\r",
  "   💡 You can switch providers temporarily with /model <model> --provider <provider>.\r",
  " ─  ⚕ Hermes  ───────────────────────────────────────────────────────────────── \r",
  "                                                                                \r",
  " Billing or credits exhausted: HTTP 402: Insufficient credits: billing required \r",
  "                                                                                \r",
  " Custom reported that billing, credits, or account entitlement is exhausted for \r",
  " mock-model.                                                                    \r",
  " Add credits or update billing with that provider, then retry.                  \r",
  " You can switch providers temporarily with /model <model> --provider            \r",
  " <provider>.                                                                    \r",
  "                                                                                \r",
  " ────────────────────────────────────────────────────────────────────────────── \r",
  " ─ ⚡ Out of credits ────────────────────────────────────────────────────────── \r",
  "                                                                                \r",
  "     Add credits with Custom.                                                   \r",
  "     Or switch providers with /model <model> --provider <provider>.             \r",
  "                                                                                \r",
  " ────────────────────────────────────────────────────────────────────────────── \r",
  "",
  "Resume this session with:",
  "  hermes --resume 20260101_120000_a1b2c3",
  "  hermes -c \"Mock title\"",
  "",
  "Session:        20260101_120000_a1b2c3",
  "Title:          Mock title",
  "Duration:       3s",
  "Messages:       1 (1 user, 0 tool calls)",
  "",
].join("\n");

/** A non-retryable provider error (HTTP 400): narration ending in a terminal cross mark, then the error Panel. */
export const REAL_FAILED_400: string = [
  "Query: Fix the null check in session.ts and report.",
  "Initializing agent...\r",
  "  ⚠ tirith security scanner enabled but not available — command scanning will use pattern matching only\r",
  "────────────────────────────────────────\r",
  "",
  "⚠️  API call failed (attempt 1/3): BadRequestError [HTTP 400]\r",
  "   🔌 Provider: custom  Model: mock-model\r",
  "   🌐 Endpoint: http://provider.example.com/v1\r",
  "   📝 Error: HTTP 400: Invalid request: unsupported parameter\r",
  "   📋 Details: {'message': 'Invalid request: unsupported parameter', 'type': 'invalid_request_error', 'code': 'invalid_request_error'}\r",
  "   ⏱️  Elapsed: 0.40s  Context: 2 msgs, ~1,302 tokens\r",
  "❌ Non-retryable error (HTTP 400): HTTP 400: Invalid request: unsupported parameter\r",
  "❌ Non-retryable client error (HTTP 400). Aborting.\r",
  "   🔌 Provider: custom  Model: mock-model\r",
  "   🌐 Endpoint: http://provider.example.com/v1\r",
  "   💡 This type of error won't be fixed by retrying.\r",
  " ─  ⚕ Hermes  ───────────────────────────────────────────────────────────────── \r",
  "                                                                                \r",
  " HTTP 400: Invalid request: unsupported parameter                               \r",
  "                                                                                \r",
  " ────────────────────────────────────────────────────────────────────────────── \r",
  "",
  "Resume this session with:",
  "  hermes --resume 20260101_120000_a1b2c3",
  "  hermes -c \"Mock title\"",
  "",
  "Session:        20260101_120000_a1b2c3",
  "Title:          Mock title",
  "Duration:       3s",
  "Messages:       1 (1 user, 0 tool calls)",
  "",
].join("\n");

/** A rate limit that survived all retries (HTTP 429): three failed attempts, then the error Panel. */
export const REAL_FAILED_429_AFTER_RETRIES: string = [
  "Query: Fix the null check in session.ts and report.",
  "Initializing agent...\r",
  "  ⚠ tirith security scanner enabled but not available — command scanning will use pattern matching only\r",
  "────────────────────────────────────────\r",
  "",
  "⚠️  API call failed (attempt 1/3): RateLimitError [HTTP 429]\r",
  "   🔌 Provider: custom  Model: mock-model\r",
  "   🌐 Endpoint: http://provider.example.com/v1\r",
  "   📝 Error: HTTP 429: Rate limit reached for requests\r",
  "   📋 Details: {'message': 'Rate limit reached for requests', 'type': 'rate_limit_exceeded', 'code': 'rate_limit_exceeded'}\r",
  "   ⏱️  Elapsed: 0.40s  Context: 2 msgs, ~1,302 tokens\r",
  "⏱️ Rate limited. Waiting 2.4s (attempt 2/3)...\r",
  "⚠️  API call failed (attempt 2/3): RateLimitError [HTTP 429]\r",
  "   🔌 Provider: custom  Model: mock-model\r",
  "   🌐 Endpoint: http://provider.example.com/v1\r",
  "   📝 Error: HTTP 429: Rate limit reached for requests\r",
  "   📋 Details: {'message': 'Rate limit reached for requests', 'type': 'rate_limit_exceeded', 'code': 'rate_limit_exceeded'}\r",
  "   ⏱️  Elapsed: 2.81s  Context: 2 msgs, ~1,302 tokens\r",
  "⏱️ Rate limited. Waiting 4.2s (attempt 3/3)...\r",
  "⚠️  API call failed (attempt 3/3): RateLimitError [HTTP 429]\r",
  "   🔌 Provider: custom  Model: mock-model\r",
  "   🌐 Endpoint: http://provider.example.com/v1\r",
  "   📝 Error: HTTP 429: Rate limit reached for requests\r",
  "   📋 Details: {'message': 'Rate limit reached for requests', 'type': 'rate_limit_exceeded', 'code': 'rate_limit_exceeded'}\r",
  "   ⏱️  Elapsed: 7.25s  Context: 2 msgs, ~1,302 tokens\r",
  "❌ Rate limited after 3 retries — HTTP 429: Rate limit reached for requests\r",
  "   💀 Final error: HTTP 429: Rate limit reached for requests\r",
  " ─  ⚕ Hermes  ───────────────────────────────────────────────────────────────── \r",
  "                                                                                \r",
  " API call failed after 3 retries: HTTP 429: Rate limit reached for requests     \r",
  "                                                                                \r",
  " ────────────────────────────────────────────────────────────────────────────── \r",
  "",
  "Resume this session with:",
  "  hermes --resume 20260101_120000_a1b2c3",
  "  hermes -c \"Mock title\"",
  "",
  "Session:        20260101_120000_a1b2c3",
  "Title:          Mock title",
  "Duration:       10s",
  "Messages:       1 (1 user, 0 tool calls)",
  "",
].join("\n");

/** A provider server error that survived all retries (HTTP 500): three failed attempts, then the error Panel. */
export const REAL_FAILED_500_AFTER_RETRIES: string = [
  "Query: Fix the null check in session.ts and report.",
  "Initializing agent...\r",
  "  ⚠ tirith security scanner enabled but not available — command scanning will use pattern matching only\r",
  "────────────────────────────────────────\r",
  "",
  "⚠️  API call failed (attempt 1/3): InternalServerError [HTTP 500]\r",
  "   🔌 Provider: custom  Model: mock-model\r",
  "   🌐 Endpoint: http://provider.example.com/v1\r",
  "   📝 Error: HTTP 500: The server had an error while processing your request\r",
  "   ⏱️  Elapsed: 0.40s  Context: 2 msgs, ~1,302 tokens\r",
  "⏳ Retrying in 2.6s (attempt 1/3)...\r",
  "⚠️  API call failed (attempt 2/3): InternalServerError [HTTP 500]\r",
  "   🔌 Provider: custom  Model: mock-model\r",
  "   🌐 Endpoint: http://provider.example.com/v1\r",
  "   📝 Error: HTTP 500: The server had an error while processing your request\r",
  "   ⏱️  Elapsed: 3.22s  Context: 2 msgs, ~1,302 tokens\r",
  "⏳ Retrying in 5.8s (attempt 2/3)...\r",
  "⚠️  API call failed (attempt 3/3): InternalServerError [HTTP 500]\r",
  "   🔌 Provider: custom  Model: mock-model\r",
  "   🌐 Endpoint: http://provider.example.com/v1\r",
  "   📝 Error: HTTP 500: The server had an error while processing your request\r",
  "   ⏱️  Elapsed: 9.05s  Context: 2 msgs, ~1,302 tokens\r",
  "❌ API failed after 3 retries — HTTP 500: The server had an error while processing your request\r",
  "   💀 Final error: HTTP 500: The server had an error while processing your request\r",
  " ─  ⚕ Hermes  ───────────────────────────────────────────────────────────────── \r",
  "                                                                                \r",
  " API call failed after 3 retries: HTTP 500: The server had an error while       \r",
  " processing your request                                                        \r",
  "                                                                                \r",
  " ────────────────────────────────────────────────────────────────────────────── \r",
  "",
  "Resume this session with:",
  "  hermes --resume 20260101_120000_a1b2c3",
  "  hermes -c \"Mock title\"",
  "",
  "Session:        20260101_120000_a1b2c3",
  "Title:          Mock title",
  "Duration:       12s",
  "Messages:       1 (1 user, 0 tool calls)",
  "",
].join("\n");

/** No provider credentials configured: the CLI prints a hint and exits before any turn (exit code 0). */
export const REAL_EARLY_EXIT_NO_CREDENTIALS: string = [
  "Query: Fix the null check in session.ts and report.",
  "",
  "⚠️  No API key found for provider 'openrouter'.",
  "   Run 'hermes model' to choose a provider, or 'hermes setup' for first-time setup.",
  "",
  "Goodbye! ⚕",
  "",
].join("\n");

/** --resume pointed at a session that does not exist: the CLI prints a message and exits before any turn (exit code 0). */
export const REAL_EARLY_EXIT_SESSION_NOT_FOUND: string = [
  "Query: Fix the null check in session.ts and report.",
  "Initializing agent...\r",
  "Session not found: 20200101_000000_nosuch\r",
  "Use a session ID from a previous CLI run (hermes sessions list).\r",
  "",
  "Goodbye! ⚕",
  "",
].join("\n");
